### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by WouterVanGoey** [njm222/tessellator#41]
First time loading the page everything worked, now I just get this error:

> **Application error**
> An error occurred in the application and your page could not be
> served. If you are the application owner, check your logs for details.
> You can do this from the Heroku CLI with the command  `heroku logs --tail`

![image](https://user-images.githubusercontent.com/6655152/197734637-0e3fa0c9-c64b-45d8-ab2c-8760aa0d6e5a.png)

**Comment by njm222** [comment]
Hey thanks for checking out tessellator! 

This happens towards the end of the month because the site sometimes runs out of free hosting for the month.

**Comment by cbortz** [comment]
@njm222 [As of Nov 28, 2022](https://blog.heroku.com/next-chapter), Heroku has discontinued their free tier. Perhaps [Netlify](https://www.netlify.com/) would be a suitable alternative.

**Comment by njm222** [comment]
@cbortz Ahhh thanks for the heads up, I wasn't aware.
I'll switch whenever I find time, hopefully sometime in the next week or two 🤞

**Comment by njm222** [comment]
@WouterVanGoey @cbortz 

Just deployed the initial v2 update on vercel:
https://tessellator-web.vercel.app/
